### ISSUE TITLE
Add php to file type

### ISSUE THREAD

**Issue by llocally** [wesleycole/atom-genesis-snippets#3]
add php to snippet file type e.g. ".text.html.php":

**Comment by wesleycole** [comment]
@llocally this should be all fixed and update pushed to Atom. Let me know if you have any issues with it!

**Comment by llocally** [comment]
All good. Many thanks
Alan Fuller 

 <http://locally.uk/?pk_campaign=emailsig&pk_kwd=emailimage&utm_source=emailsig&utm_medium=email&utm_content=sigimage&utm_campaign=email> 
Web design, development & support
 
t 01483 338 404 m 07714 68 16 00 
w locally.uk <http://locally.uk/?pk_campaign=emailsig&pk_kwd=emailtextlink&utm_source=emailsig&utm_medium=email&utm_content=sigtextlink&utm_campaign=email>       e alan@locally.uk <mailto:alan@locally.uk>

 <http://www.linkedin.com/in/aefuller>  <https://plus.google.com/+llocally>  <https://www.facebook.com/locallyUK>  <https://twitter.com/locallyHQ>
Office address: Export House, Cawsey Way, Woking, Surrey GU21 6QX 
Locally Digital Ltd is a company registered in England and Wales. Registered number: 07720957. Registered office: 13 Oakfields, Walton-on-thames, Surrey KT12 1EG. **Email confidentiality notice** This message is private and confidential. If you have received this message in error, please notify us and remove it from your system.
